apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-test-frontend
spec:
  selector:
    matchLabels:
      app: angular-test
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: angular-test
        tier: frontend
    spec:
      containers:
        - name: angular-test-frontend
          image: "ernom/angular-test"
          ports:
            - containerPort: 4200