apiVersion: v1
kind: Service
metadata:
  name: angular-test-frontend
spec:
  ports:
  - name: http
    port: 4200
    protocol: TCP
    targetPort: 4200
  selector:
    app: angular-test
  type: ClusterIP